# Generated by Django 4.1.7 on 2023-04-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='Profiles/default-user.png', null=True, upload_to='Profiles'),
        ),
    ]
